---
- hosts: all
  become: yes
  tasks:
    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address=192.168.30.200 --pod-network-cidr=172.16.0.0/16
    - name: Setup kubeconfig for vagrant user
      command: "{{ item }}"
      with_items:
       - mkdir -p /home/vagrant/.kube
       - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
       - chown vagrant:vagrant /home/vagrant/.kube/config
    - name: Installing the weave network
      become: False
      shell: 
         cmd: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&env.NO_MASQ_LOCAL=1"
    - name: Generate Cluster join command
      command: kubeadm token create --print-join-command
      register: join_command
    - name: Copy join command to local file
      copy: content="{{ join_command.stdout_lines[0] }}" dest="/tmp/join-command" owner=vagrant group=vagrant

      


    - name: Installation of Metallb (LoadBalancer Setup)
      shell: 
        cmd: "kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e 's/strictARP: false/strictARP: true/'| kubectl apply -f - -n kube-system"
      become: no    

    - name: Adding Metallb namespace
      become: no
      command: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml
    - name: Adding Metallb 
      become: no
      command: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml
    - name: Adding Firsttime
      become: no
      shell:
        cmd: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
    - name: Adding the IP Range
      copy:
        content: |
            apiVersion: v1
            kind: ConfigMap
            metadata:
              namespace: metallb-system
              name: config
            data:
              config: |
                address-pools:
                - name: default
                  protocol: layer2
                  addresses:
                  - 192.168.30.20-192.168.30.50
        dest: /tmp/ip.yaml
        mode: 0644
    - command: kubectl apply -f /tmp/ip.yaml
      become: no